FROM mcr.microsoft.com/dotnet/core/sdk:3.1.302-alpine3.12 AS build
WORKDIR /app/src
COPY /src .
RUN dotnet build joseki.azsk-scanner.sln -c Release


FROM build AS testrunner
WORKDIR /app/src/tests
ENTRYPOINT ["dotnet","test","--logger:trx;LogFileName=test_results.xml","--no-build","-c","Release","-r","/app/testresults"]


FROM build AS publish-cli
WORKDIR /app/src
RUN dotnet publish cli/cli.csproj -c Release -o /app/publish --no-restore --no-build


FROM mcr.microsoft.com/dotnet/core/runtime:3.1.6-alpine3.12 AS cliapp

# install the requirements for powershell
RUN apk add --no-cache \
    ca-certificates=~20191127 \
    less=~551 \
    ncurses-terminfo-base=~6.2 \
    krb5-libs=~1.18.2 \
    libgcc=~9.3.0 \
    libintl=~0.20.2 \
    libssl1.1=~1.1.1 \
    libstdc++=~9.3.0 \
    lttng-ust=~2.12.0 \
    tzdata=2020a-r0 \
    userspace-rcu=~0.12.1 \
    zlib=~1.2.11 \
    icu-libs=~67.1 \
    curl=~7.69.1

# Download the powershell '.tar.gz' archive
RUN curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/powershell-7.0.3-linux-alpine-x64.tar.gz -o /tmp/powershell.tar.gz

# Create the target folder where powershell will be placed
RUN mkdir -p /opt/microsoft/powershell/7

# Expand powershell to the target folder
RUN tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7

# Set execute permissions
RUN chmod +x /opt/microsoft/powershell/7/pwsh

# Create the symbolic link that points to pwsh
RUN ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/powershell

# Install az-sk module
ENV AZSK_VERSION=4.11.0
RUN powershell -Command Install-Module AzSK -RequiredVersion "$AZSK_VERSION" -Force

WORKDIR /app
COPY --from=publish-cli /app/publish .

COPY ps/azsk.ps1 /app/azsk.ps1

ENTRYPOINT ["dotnet","cli.dll"]
