---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-azsk-cfg
  namespace: joseki
  labels:
    app: scanner-azsk
    module: scanners
    version: '#{azsk.imageTag}#'
data:
  scanner-azsk-config.yaml:  |
    scanner:
      !azsk-scanner
      id: #{azsk.scannerId}#
      version: #{azsk.imageTag}#
      periodicity: 0 2 * * *
      azSkVersion: 4.7.0
      auditScriptPath: /app/azsk.ps1
      tenantId: #{azsk.tenantId}#
      servicePrincipalId: #{azsk.spId}#
      servicePrincipalPassword: #{azsk.spPassword}#

    exporter:
      !az-blob
      basePath: https://#{azsk.storageAccountName}#.blob.core.windows.net/#{azsk.containerName}#
      sas: #{azsk.storageSas}#
      heartbeatPeriodicity: 86400

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner-azsk
  namespace: joseki
  labels:
    app: scanner-azsk
    module: scanners

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: scanner-azsk
  labels:
    app: scanner-azsk
    module: scanners

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: scanner-azsk
  labels:
    app: scanner-azsk
    module: scanners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scanner-azsk
subjects:
  - kind: ServiceAccount
    name: scanner-azsk
    namespace: joseki

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scanner-azsk
  namespace: joseki
  labels:
    app: scanner-azsk
    module: scanners
    version: '#{azsk.imageTag}#'
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner-azsk
            image: deepnetwork/joseki-scanner-azsk:#{azsk.imageTag}#
            imagePullPolicy: Always
            args: ["--config", "/app/config.az.yaml", "--subscriptions", #{azsk.subscriptions}#]
            volumeMounts:
            - name: config
              mountPath: /app/config.az.yaml
              subPath: scanner-azsk-config.yaml
              readOnly: true
          volumes:
            - name: config
              configMap:
                name: scanner-azsk-cfg
          restartPolicy: Never
          serviceAccountName: scanner-azsk