// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace joseki.db.Migrations
{
#pragma warning disable 1591
    public partial class UsedPackageColumnInScan2CVE : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "UsedPackage",
                table: "ImageScanResultToCve",
                nullable: true);

            migrationBuilder.Sql(
                @"
            UPDATE [dbo].[ImageScanResultToCve]
            SET 
                [dbo].[ImageScanResultToCve].[UsedPackage] = [dbo].[Cve].[PackageName]
            FROM 
                [dbo].[ImageScanResultToCve]
                INNER JOIN [dbo].[Cve] on [dbo].[Cve].[Id] = [dbo].[ImageScanResultToCve].CveId
            ");

            migrationBuilder.AlterColumn<string>(
                name: "UsedPackage",
                table: "ImageScanResultToCve",
                nullable: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "UsedPackage",
                table: "ImageScanResultToCve");
        }
    }
#pragma warning restore 1591
}
