// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using joseki.db;

namespace joseki.db.Migrations
{
#pragma warning disable 612, 618, 1591
    [DbContext(typeof(JosekiDbContext))]
    [Migration("20200312133728_Knowledgebase_CheckResultTooltips")]
    partial class Knowledgebase_CheckResultTooltips
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("joseki.db.entities.AuditEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("undefined-id");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("undefined-name");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScannerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "ScannerId")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Include", new[] { "AuditId" });

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("joseki.db.entities.CheckEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CheckId")
                        .IsUnique();

                    b.ToTable("Check");
                });

            modelBuilder.Entity("joseki.db.entities.CheckResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CheckId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("CheckId");

                    b.HasIndex("ComponentId", "Value")
                        .HasFilter("[VALUE] = 'InProgress'");

                    b.ToTable("CheckResult");
                });

            modelBuilder.Entity("joseki.db.entities.CveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("References")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CveId")
                        .IsUnique();

                    b.ToTable("Cve");
                });

            modelBuilder.Entity("joseki.db.entities.ImageScanResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImageTag", "Date")
                        .IsUnique();

                    b.ToTable("ImageScanResult");
                });

            modelBuilder.Entity("joseki.db.entities.ImageScanToCveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CveId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsedPackage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsedPackageVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CveId");

                    b.HasIndex("ScanId");

                    b.ToTable("ImageScanResultToCve");
                });

            modelBuilder.Entity("joseki.db.entities.KnowledgebaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasFilter("[ItemId] IS NOT NULL");

                    b.ToTable("Knowledgebase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Kubernetes provides a great deal of configurability when it comes to the security of your workloads. A key principle here involves limiting the level of access any individual workload has. Polaris has validations for a number of best practices, mostly focused on ensuring that unnecessary access has not been granted to an application workload.",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "polaris.security"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Networking configuration in Kubernetes can be quite powerful. Polaris validates that pods are not configured to have access to sensitive host networking configuration. There are certain use cases such as a container overlay network like Calico, where this level of access is required, but the majority of workloads running on Kubernetes should not need this.",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "polaris.networking"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Configuring resource requests and limits for workloads running in Kubernetes helps ensure that every container will have access to all the resources it needs. These are also a crucial part of cluster autoscaling logic, as new nodes are only spun up when there is insufficient capacity on existing infrastructure for new pod(s). By default, Polaris validates that resource requests and limits are set, it also includes optional functionality to ensure these requests and limits fall within specified ranges.",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "polaris.resources"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Properly configured health checks can ensure the long term availability and reliability of your application running in Kubernetes. Polaris validates that health checks are configured for each pod running in your cluster.",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "polaris.healthchecks"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Images are the backbone of any Kubernetes cluster, containing the applications that run in each container. Polaris validates that images are configured with specific tags instead of just pulling the latest image on each run. This is important for the stability and security of your workloads.",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "polaris.images"
                        },
                        new
                        {
                            Id = 6,
                            Content = "A set of verifications related to Azure Analysis services. It enforces: sensitive data encryption, proper RBAC and AAD configuration, backup setup. the entire list is at https://aka.ms/azsktcp/analysisservices",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.analysisservices"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Verifies if Logic App connectors use AAD-based authentication and data transit across connectors use encrypted channel. The entire list is at https://aka.ms/azsktcp/logicapps",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.apiconnection"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Group of checks for Azure API Management service: RBAC, alerts, enabled diagnostic-logs, TLS configuration, secrets management and others. The entire list is at https://aka.ms/azsktcp/apim",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.apimanagement"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Verifies if Azure App Service is properly configured: SSL, Active directory configuration, secrets management, webhooks, alerts, etc. The entire list is at https://aka.ms/azsktcp/appservice",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.appservice"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Azure ApplicationProxy related checks: AAD, personal-data management, gateway-machine configuration. The entire list is at https://github.com/azsk/DevOpsKit-docs/blob/master/02-Secure-Development/ControlCoverage/Feature/ApplicationProxy.md",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.applicationproxy"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Verifies that Azure Automation is properly setup: variables are encrypted, webhooks are safe, log-analytics integration. The entire list is at https://aka.ms/azsktcp/automation",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.automation"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Azure Batch service verifications: proper ADD permissions are set, data is encrypted, alerts are set. The entire list is at https://aka.ms/azsktcp/batch",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.batch"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Group of checks for Azure Bot service: traffic management, enabled logging. The entire list is at https://github.com/azsk/DevOpsKit-docs/blob/master/02-Secure-Development/ControlCoverage/Feature/BotService.md",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.botservice"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Azure CDN checks: RBAC and HTTPS configuration. The entire list is at https://aka.ms/azsktcp/cdn",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.cdn"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Azure Cloud Service verification: HTTPS configuration, switched-off remote debugging, OS version, RDP, and others. The entire list is at https://aka.ms/azsktcp/cloudservice",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.cloudservice"
                        },
                        new
                        {
                            Id = 16,
                            Content = "A group of checks related to Azure Container Instances. The entire list is at https://aka.ms/azsktcp/containerinstances",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.containerinstances"
                        },
                        new
                        {
                            Id = 17,
                            Content = "Verifies Azure Container Registry: admin user is disabled, RBAC, image-vulnerabilities scans, logs, and others. The entire list is at https://aka.ms/azsktcp/containerregistry",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.containerregistry"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Azure CosmosDB should: use firewall, use only trusted network, has failover and backups setuped. The entire list is at https://aka.ms/azsktcp/cosmosdb",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.cosmosdb"
                        },
                        new
                        {
                            Id = 19,
                            Content = "A set of checks for Azure Databricks: secrets management, RBAC and users management. The entire list is at https://github.com/azsk/DevOpsKit-docs/blob/master/02-Secure-Development/ControlCoverage/Feature/Databricks.md",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.databricks"
                        },
                        new
                        {
                            Id = 20,
                            Content = "Azure Data Factory is properly configured: data is encrypted, keys are rotated, monitoring is enabled. The entire list is at https://aka.ms/azsktcp/datafactory",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.datafactory"
                        },
                        new
                        {
                            Id = 21,
                            Content = "Azure Data Factory V2 configration. The entire list is at https://https://github.com/azsk/DevOpsKit-docs/blob/master/02-Secure-Development/ControlCoverage/Feature/DataFactoryV2.md",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.datafactoryv2"
                        },
                        new
                        {
                            Id = 22,
                            Content = "Azure Data Lake configuration: proper AAD usage, data is encrypted and backup-ed, monitoring is enabled. The entire list is at https://aka.ms/azsktcp/datalakeanalytics",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.datalakeanalytics"
                        },
                        new
                        {
                            Id = 23,
                            Content = "Azure Data Lake Store configuration: AAD, access-control list, firewall, and others. The entire list is at https://aka.ms/azsktcp/datalakestore",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.datalakestore"
                        },
                        new
                        {
                            Id = 24,
                            Content = "Groups Azure Event Hub verifications: access-control, data-encryption, logs. The entire list is at https://aka.ms/azsktcp/eventhub",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.eventhub"
                        },
                        new
                        {
                            Id = 25,
                            Content = "Azure ERvNet configuration. The entire list is at https://aka.ms/azsktcp/ervnet",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.ervnet"
                        },
                        new
                        {
                            Id = 26,
                            Content = "Azure HDInsights config: data-encryption, proper networking configuration, HDI version, and others. The entire list is at https://azsk.azurewebsites.net/02-Secure-Development/ControlCoverage/Feature/HDInsight.html",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.hdinsight"
                        },
                        new
                        {
                            Id = 27,
                            Content = "Azure Key Vault config: RBAC, secrets rotation, logging. the entire list is at https://azsk.azurewebsites.net/02-Secure-Development/ControlCoverage/Feature/KeyVault.html",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.keyvault"
                        },
                        new
                        {
                            Id = 28,
                            Content = "Azure AKS configuration: RBAC amd AAD integration, k8s version, public access, etc. The entire list is at https://aka.ms/azsktcp/KubernetesService",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.kubernetesservice"
                        },
                        new
                        {
                            Id = 29,
                            Content = "Azure Load Balancer config: RBAC, logs, public-ips. the entire list is at https://aka.ms/azsktcp/loadbalancer",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.loadbalancer"
                        },
                        new
                        {
                            Id = 30,
                            Content = "Azure Log Analytics config",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.loganalytics"
                        },
                        new
                        {
                            Id = 31,
                            Content = "Verifies if Logic App connectors use AAD-based authentication and data transit across connectors use encrypted channel. The entire list is at https://aka.ms/azsktcp/logicapps",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.logicapps"
                        },
                        new
                        {
                            Id = 32,
                            Content = "Azure Notification Hub configuration: access-policies and RBAC, logging and recovery policies. The entire list is at https://aka.ms/azsktcp/notificationhub",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.notificationhub"
                        },
                        new
                        {
                            Id = 33,
                            Content = "Azure on-premise data-gateway configuration: user permissions, logging, OS hardening. The entire list is at https://aka.ms/azsktcp/odg",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.odg"
                        },
                        new
                        {
                            Id = 34,
                            Content = "Azure managed Redis cache configuration: firewall and user-access, keys rotation, vnet. The entire list is at https://aka.ms/azsktcp/rediscache",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.rediscache"
                        },
                        new
                        {
                            Id = 35,
                            Content = "Azure Search service configuration: access-control, data encryption, replication. The entire list is at https://aka.ms/azsktcp/search",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.search"
                        },
                        new
                        {
                            Id = 36,
                            Content = "Azure Service Bus service configuration: access-policies and tokens, data-encryption, recovery, etc. The entire list is at https://aka.ms/azsktcp/servicebus",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.servicebus"
                        },
                        new
                        {
                            Id = 37,
                            Content = "Azure Service Fabric config: data replication and encryption, secrets management, size of replicas sets, AAD, and others. The entire list is at https://aka.ms/azsktcp/servicefabric",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.servicefabric"
                        },
                        new
                        {
                            Id = 38,
                            Content = "Azure Storage service configuration: public access (HTTPS, CORS, disabled anonymous access), access-management and secrets rotation, AAD. The entire list is at https://aka.ms/azsktcp/storage",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.storage"
                        },
                        new
                        {
                            Id = 39,
                            Content = "Azure Stream Analytics config: RBAC, logs, backup. The entire list is at https://aka.ms/azsktcp/streamanalytics",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.streamanalytics"
                        },
                        new
                        {
                            Id = 40,
                            Content = "Azure subscription related checks: amount of admin accounts, permissions and users, certificates, MFA, and others. The entire list is at https://aka.ms/azsktcp/sshealth",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.subscriptioncore"
                        },
                        new
                        {
                            Id = 41,
                            Content = "Azure managed MS SQL Server configuration: user access, encryption, firewall. The entire list is at https://aka.ms/azsktcp/sqldatabase",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.sqldatabase"
                        },
                        new
                        {
                            Id = 42,
                            Content = "Azure Traffic Manager HTTPS and RBAC configuration. The entire list is at https://aka.ms/azsktcp/trafficmanager",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.trafficmanager"
                        },
                        new
                        {
                            Id = 43,
                            Content = "Azure VM config: OS, network, disk, policies. The entire list is at https://aka.ms/azsktcp/virtualmachine",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.virtualmachine"
                        },
                        new
                        {
                            Id = 44,
                            Content = "Azure VM Scale Sets config: version, enabled antimalware, VNet and RBAC, etc. The entire list is at https://aka.ms/azsktcp/virtualmachinescaleset",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.virtualmachinescaleset"
                        },
                        new
                        {
                            Id = 45,
                            Content = "Azure Network configuration: IPs, RBAC, security-groups. The entire list is at https://aka.ms/azsktcp/virtualnetwork",
                            DateCreated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            DateUpdated = new DateTime(2020, 3, 9, 12, 56, 38, 559, DateTimeKind.Utc).AddTicks(793),
                            ItemId = "azsk.virtualnetwork"
                        },
                        new
                        {
                            Id = 46,
                            Content = "NoData means one of the following: 1. Joseki is not able to perform the Check due to not sufficient permissions; 2. Docker Image scanner was not able to complete a scan; 3. the Check requires a manual step to be performed",
                            DateCreated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            DateUpdated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            ItemId = "metadata.checks_nodata_description"
                        },
                        new
                        {
                            Id = 47,
                            Content = "Warning indicates when Joseki found, likely, a not critical issue with a particular infrastructure component",
                            DateCreated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            DateUpdated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            ItemId = "metadata.checks_warning_description"
                        },
                        new
                        {
                            Id = 48,
                            Content = "Failed check highlights the most critical issues that should be reviewed first",
                            DateCreated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            DateUpdated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            ItemId = "metadata.checks_failed_description"
                        },
                        new
                        {
                            Id = 49,
                            Content = "You're good ;) A component satisfies verified rule",
                            DateCreated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            DateUpdated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            ItemId = "metadata.checks_passed_description"
                        },
                        new
                        {
                            Id = 50,
                            Content = "The audit score. It indicates how close the infrastructure is to known best-practices configuration. The formula excludes NoData checks, gives doubled weight to Passed and Failed results: (Passed*2)/(Failed*2 + Passed*2 + Warning)",
                            DateCreated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            DateUpdated = new DateTime(2020, 3, 12, 13, 33, 48, 595, DateTimeKind.Utc).AddTicks(7551),
                            ItemId = "metadata.checks_score_description"
                        });
                });

            modelBuilder.Entity("joseki.db.entities.MetadataAzureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("JSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuditId")
                        .IsUnique();

                    b.ToTable("MetadataAzure");
                });

            modelBuilder.Entity("joseki.db.entities.MetadataKubeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("JSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuditId")
                        .IsUnique();

                    b.ToTable("MetadataKube");
                });

            modelBuilder.Entity("joseki.db.entities.CheckResultEntity", b =>
                {
                    b.HasOne("joseki.db.entities.AuditEntity", "Audit")
                        .WithMany("CheckResults")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("joseki.db.entities.CheckEntity", "Check")
                        .WithMany()
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("joseki.db.entities.ImageScanToCveEntity", b =>
                {
                    b.HasOne("joseki.db.entities.CveEntity", "CVE")
                        .WithMany()
                        .HasForeignKey("CveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("joseki.db.entities.ImageScanResultEntity", "ImageScan")
                        .WithMany("FoundCVEs")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("joseki.db.entities.MetadataAzureEntity", b =>
                {
                    b.HasOne("joseki.db.entities.AuditEntity", "Audit")
                        .WithOne("MetadataAzure")
                        .HasForeignKey("joseki.db.entities.MetadataAzureEntity", "AuditId");
                });

            modelBuilder.Entity("joseki.db.entities.MetadataKubeEntity", b =>
                {
                    b.HasOne("joseki.db.entities.AuditEntity", "Audit")
                        .WithOne("MetadataKube")
                        .HasForeignKey("joseki.db.entities.MetadataKubeEntity", "AuditId");
                });
        }
    }
#pragma warning restore 612, 618, 1591
}
