resources:
- scanner-azsk.yaml
generatorOptions:
  labels: 
    app: scanner-azsk
    module: scanners
    version: '#{azsk.imageTag}#'
configMapGenerator:
- name: scanner-azsk-cfg
  namespace: joseki
  behavior: replace
  files:
  - scanner-azsk-config.yaml
