---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-azsk-cfg
  namespace: joseki
  labels:
    app: scanner-azsk
    module: scanners
    version: '#{azsk.imageTag}#'
data:
  scanner-azsk-config.yaml:  |
    to-be-replaced

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scanner-azsk
  namespace: joseki
  labels:
    app: scanner-azsk
    module: scanners
    version: '#{azsk.imageTag}#'
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner-azsk
            image: deepnetwork/joseki-scanner-azsk:#{azsk.imageTag}#
            imagePullPolicy: Always
            args: ["--config", "/app/config.az.yaml", "--subscriptions", #{azsk.subscriptions}#]
            volumeMounts:
              - name: config
                mountPath: /app/config.az.yaml
                subPath: scanner-azsk-config.yaml
                readOnly: true 
            env:
              - name: SCANNER_VERSION
                value: "#{azsk.imageTag}#"
          volumes:
            - name: config
              configMap:
                name: scanner-azsk-cfg
          restartPolicy: Never
          serviceAccountName: scanner-azsk