FROM mcr.microsoft.com/dotnet/core/sdk:3.1.102-alpine3.11 AS build
WORKDIR /app/src
COPY ./joseki.be .
RUN dotnet build joseki.be.sln -c Release


FROM build AS publish
WORKDIR /app/src
RUN dotnet publish webapp/webapp.csproj -c Release -o /app/publish --no-restore --no-build


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.2-alpine3.11 AS webapp
WORKDIR /app
COPY --from=publish /app/publish .

# Disable invariant mode due SqlClient exceptions
# https://github.com/dotnet/SqlClient/issues/220
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# Change to 8080 because 80 requires elevated privileges
ENV ASPNETCORE_URLS="http://*:8080"
EXPOSE 8080

ENV USER=josekibe
ENV UID=10001
ENV GID=10001
RUN addgroup "$USER" --gid "$GID" \
    && adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --ingroup "$USER" \
    --no-create-home \
    --uid "$UID" \
    "$USER"
RUN chown -R "$USER":"$USER" /app

# disable managed debugging, which requires user access to /tmp directory owned by root
ENV COMPlus_EnableDiagnostics=0

USER "$USER"
ENTRYPOINT ["dotnet","webapp.dll"]