FROM golang:1.13.7-alpine3.11 AS build-env
WORKDIR /go/src/github.com/deepnetworkgmbh/joseki/src/scanners/polaris

COPY go.mod go.sum ./
ENV GOMOD=/go/src/github.com/deepnetworkgmbh/joseki/src/scanners/polaris/go.mod
RUN go mod download

COPY . .
RUN go build -o scanner-polaris .

RUN apk --no-cache add ca-certificates

ENTRYPOINT ["./scanner-polaris"]
