FROM golang:1.14.1-alpine3.11 AS cliapp
WORKDIR /go/src/github.com/deepnetworkgmbh/joseki/src/scanners/polaris

COPY go.mod go.sum ./
ENV GOMOD=/go/src/github.com/deepnetworkgmbh/joseki/src/scanners/polaris/go.mod
RUN go mod download

COPY . .
RUN go build -o scanner-polaris .

RUN apk --no-cache add ca-certificates=20191127-r1

ENTRYPOINT ["./scanner-polaris"]
