---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-scanner-azsk-cfg
  namespace: joseki
  labels:
    app: fake-scanner-azsk
    module: scanners
    version: '#{azsk.imageTag}#'
data:
  fake-scanner-azsk-config.yaml:  |
    to-be-replaced

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fake-scanner-azsk
  namespace: joseki
  labels:
    app: fake-scanner-azsk
    module: scanners
    version: '#{azsk.imageTag}#'
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: config
            configMap:
              name: fake-scanner-azsk-cfg
          - name: test-data
            configMap:
              name: azsk-test-data
          - name: shared-data
            emptyDir: {}
          restartPolicy: Never
          serviceAccountName: scanner-azsk
          initContainers:
            - name: extract-test-data
              image: alpine:3.11.5
              command: ["/bin/sh","-c", "tar -xf /tmp/azsk_test_data.tar.xz -C /usr/share"]
              volumeMounts:
                - name: test-data
                  mountPath: /tmp/azsk_test_data.tar.xz
                  subPath: azsk_test_data.tar.xz
                  readOnly: true
                - name: shared-data
                  mountPath: /usr/share/azsk_test_data
          containers:
            - name: fake-scanner-azsk
              volumeMounts:
                - name: config
                  mountPath: /app/config.az.yaml
                  subPath: fake-scanner-azsk-config.yaml
                  readOnly: true
                - name: shared-data
                  mountPath: /usr/share/azsk_test_data
              env:
                - name: SCANNER_VERSION
                  value: "#{azsk.imageTag}#"
              image: deepnetwork/joseki-scanner-azsk:#{azsk.imageTag}#
              imagePullPolicy: Always
              args: ["--config", "/app/config.az.yaml", "--subscriptions", "5720db52-2fb2-4568-bb63-20c7c0dd0a3e"]
