scanner:
  id: 8fc1b601-d5a2-466d-8236-c747c1dc02a2
  cluster-id: 8fc1b601-d5a2-466d-8236-c747c1dc02a2
  periodicity: "0 2 * * *"
  heartbeat-periodicity: 86400
polaris:
  configPath: ./examples/polaris-config.yaml
blobStorageType: azure-blob-storage
azureBlob:
  storageBaseUrl: https://BLOB_NAME.blob.core.windows.net/CONTAINER_NAME
  sasToken: insert-sas-token-here
logFormat: plain-text