# build stage
FROM node:12.18.0-alpine3.12 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./

RUN npm install
RUN npm install @vue/cli@4.1.0 -g

COPY . .
RUN npm run build

# production stage
FROM nginx:1.19.0-alpine as webapp
COPY --from=build /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]