---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: joseki
  name: scanner-trivy-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-trivy-cfg
  namespace: joseki
  labels:
    app: scanner-trivy
    module: scanners
data:
  scanner-trivy-config.yaml:  |-
    to-be-replaced

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: joseki
  name: scanner-trivy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: scanner-trivy
      module: scanners
  template:
    metadata:
      labels:
        app: scanner-trivy
        module: scanners
    spec:
      containers:
      - name: scanner-trivy
        image: 'deepnetwork/joseki-scanner-trivy:#{trivy.imageTag}#'
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200M"
            cpu: "300m"
          limits:
            memory: "500M"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        ports:
          - containerPort: 8080
            name: main-http
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: false
        volumeMounts:
          - name: scanner-cfg-volume
            mountPath: /app/scanner-trivy-config.yaml
            subPath: scanner-trivy-config.yaml
          - name: storage-volume
            mountPath: "/app/.cache"
        env:
          - name: IMAGE_SCANNER_CONFIG_FILE_PATH
            value: "/app/scanner-trivy-config.yaml"
          - name: SCANNER_VERSION
            value: "#{trivy.imageTag}#"
      securityContext:
        fsGroup: 10001
      volumes:
        - name: scanner-cfg-volume
          configMap:
            name: scanner-trivy-cfg
            defaultMode: 0777
            items:
              - key: scanner-trivy-config.yaml
                path: scanner-trivy-config.yaml
        - name: storage-volume
          persistentVolumeClaim:
            claimName: scanner-trivy-storage
