---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner-polaris
  namespace: joseki
  labels:
    app: scanner-polaris
    module: scanners

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: scanner-polaris
  labels:
    app: scanner-polaris
    module: scanners
rules:
  - apiGroups:
      - ''
    resources:
      - 'nodes'
    verbs:
      - 'get'
      - 'list'

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: scanner-polaris
  labels:
    app: scanner-polaris
    module: scanners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scanner-polaris
subjects:
  - kind: ServiceAccount
    name: scanner-polaris
    namespace: joseki

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: scanner-polaris-view
  labels:
    app: scanner-polaris
    module: scanners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: scanner-polaris
    namespace: joseki
