---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-polaris-cfg
  namespace: joseki
  labels:
    app: scanner-polaris
    module: scanners
data:
  config_scanner.yaml:  |
    to-be-replaced
  config_polaris.yaml:  |
    to-be-replaced

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scanner-polaris
  namespace: joseki
  labels:
    app: scanner-polaris
    module: scanners
    version: '#{polaris.imageTag}#'
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner-polaris
            image: 'deepnetwork/joseki-scanner-polaris:#{polaris.imageTag}#'
            imagePullPolicy: Always
            args: ["--config", "/app/config_scanner.yaml"]
            volumeMounts:
              - name: config
                mountPath: /app/config_scanner.yaml
                subPath: config_scanner.yaml
                readOnly: true
              - name: config
                mountPath: /app/config_polaris.yaml
                subPath: config_polaris.yaml
                readOnly: true
            env:
              - name: SCANNER_VERSION
                value: "#{polaris.imageTag}#"
          volumes:
            - name: config
              configMap:
                name: scanner-polaris-cfg
          restartPolicy: Never
          serviceAccountName: scanner-polaris