resources:
- fe.yaml
generatorOptions:
  labels: 
    app: joseki-frontend
    version: '#{fe.imageTag}#'
configMapGenerator:
- name: frontend-config
  namespace: joseki
  behavior: replace
  files:
  - config.json

