name: backend_validate_pr

on: 
  pull_request:
    branches:
    - master
    paths:
      - '.github/workflows/backend_pr.yml'
      - 'src/backend/**'
      - '!src/backend/*.md'

jobs:
  validate-pr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.2.0

    - name: Set env vars
      run: |
        echo "::set-env name=SERVICE_ROOT::src/backend/"
        echo "::set-env name=DOCKERFILE_PATH::src/backend/dockerfile"

        SHA8=$(echo $GITHUB_SHA | cut -c1-8)
        tests_tag="deepnetwork/joseki-backend:$SHA8-tests"
        tests_dir="$HOME/be_testresults"
        echo "::set-env name=TESTS_TAG::$tests_tag"
        echo "::set-env name=TESTS_DIR::$tests_dir"

    - name: lint dockerfile
      uses: brpaz/hadolint-action@2d3af3e
      with:
        dockerfile: ${{ env.DOCKERFILE_PATH }}

    - name: run unit-tests
      run: |
        docker build -t ${{ env.TESTS_TAG }} -f ${{ env.DOCKERFILE_PATH }} --target testrunner ${{ env.SERVICE_ROOT }}
        sudo mkdir -p ${{ env.TESTS_DIR }}
        docker run --rm --mount type=bind,source=${{ env.TESTS_DIR }},target=/app/testresults ${{ env.TESTS_TAG }}

    - name: publish test results
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test_results
        path: '${{ env.TESTS_DIR }}/test_results.xml'