name: scanner_azsk_ci_master

on: 
  push:
    branches:
    - master
    paths:
      - '.github/workflows/scanner_azsk_master.yml'
      - 'src/scanners/az-sk/**'
      - '!src/scanners/az-sk/*.md'

jobs:
  build-n-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Set env vars
      run: |
        echo "SERVICE_ROOT=src/scanners/az-sk/" >> $GITHUB_ENV
        echo "DOCKERFILE_PATH=src/scanners/az-sk/dockerfile" >> $GITHUB_ENV

        docker_repository="deepnetwork/joseki-scanner-azsk"
        echo "DOCKER_REPOSITORY=$docker_repository" >> $GITHUB_ENV

        version=$(cat src/scanners/az-sk/version)
        SHA8=$(echo $GITHUB_SHA | cut -c1-8)
        tag_dev="$version-sha-$SHA8"
        echo "VERSION_TAG=$version" >> $GITHUB_ENV
        echo "DEV_TAG=$tag_dev" >> $GITHUB_ENV

        tests_tag="$docker_repository:$tag_dev.tests"
        tests_dir="$HOME/azsk_testresults"
        echo "TESTS_TAG=$tests_tag" >> $GITHUB_ENV
        echo "TESTS_DIR=$tests_dir" >> $GITHUB_ENV

    - name: lint dockerfile
      uses: brpaz/hadolint-action@v1.1.0
      with:
        dockerfile: ${{ env.DOCKERFILE_PATH }}

    - name: run unit-tests
      run: |
        docker build -t ${{ env.TESTS_TAG }} -f ${{ env.DOCKERFILE_PATH }} --target testrunner ${{ env.SERVICE_ROOT }}
        sudo mkdir -p ${{ env.TESTS_DIR }}
        docker run --rm --mount type=bind,source=${{ env.TESTS_DIR }},target=/app/testresults ${{ env.TESTS_TAG }}

    - name: publish test results
      uses: actions/upload-artifact@v2.2.0
      with:
        name: test_results
        path: '${{ env.TESTS_DIR }}/test_results.xml'

    - name: build dockerimage
      uses: docker/build-push-action@v1.1.0
      with:
        path: ${{ env.SERVICE_ROOT }}
        dockerfile: ${{ env.DOCKERFILE_PATH }}
        target: cliapp
        repository: ${{ env.DOCKER_REPOSITORY }}
        tags: ${{ env.VERSION_TAG }}, ${{ env.DEV_TAG }}, edge
        add_git_labels: true
        push: false

    - name: scan image for CVEs
      uses: 'docker://aquasec/trivy:0.9.1'
      with:
        args: --exit-code 1 --severity HIGH,CRITICAL --no-progress "${{ env.DOCKER_REPOSITORY }}:${{ env.DEV_TAG }}"

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push dockerimage
      run: |
        docker push "${{ env.DOCKER_REPOSITORY }}:${{ env.DEV_TAG }}"
        docker push "${{ env.DOCKER_REPOSITORY }}:${{ env.VERSION_TAG }}"
        docker push "${{ env.DOCKER_REPOSITORY }}:edge"

    - name: deploy to k8s
      env:
        IMAGE_TAG: ${{ env.DEV_TAG }}
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        AZSK_CONFIG_DATA: ${{ secrets.AZSK_CONFIG_DATA }}
        SUBSCRIPTIONS: ${{ secrets.AZSK_SUBSCRIPTIONS }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 --decode > /tmp/config
        export KUBECONFIG=/tmp/config

        CONFIG_PATH=examples/k8s/azsk/scanner-azsk-config.yaml
        echo "$AZSK_CONFIG_DATA" | base64 --decode > $CONFIG_PATH

        sed -i 's|#{azsk.imageTag}#|'"$IMAGE_TAG"'|' examples/k8s/azsk/kustomization.yaml
        sed -i 's|#{azsk.imageTag}#|'"$IMAGE_TAG"'|' examples/k8s/azsk/scanner-azsk.yaml
        sed -i 's|#{azsk.subscriptions}#|'"$SUBSCRIPTIONS"'|' examples/k8s/azsk/scanner-azsk.yaml

        # apply rbac yaml and kustomized objects
        kubectl apply -f examples/k8s/azsk/rbac.yaml
        kubectl apply -k examples/k8s/azsk

        rm $CONFIG_PATH /tmp/config
