name: scanner_polaris_validate_pr

on: 
  pull_request:
    branches:
    - master
    paths:
      - '.github/workflows/scanner_polaris_pr.yml'
      - 'src/scanners/polaris/**'
      - '!src/scanners/polaris/*.md'

jobs:
  validate-pr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Set env vars
      run: |
        echo "SERVICE_ROOT=src/scanners/polaris/" >> $GITHUB_ENV
        echo "DOCKERFILE_PATH=src/scanners/polaris/dockerfile" >> $GITHUB_ENV
        echo "DOCKER_REPOSITORY=deepnetwork/joseki-scanner-polaris" >> $GITHUB_ENV

    - name: lint dockerfile
      uses: brpaz/hadolint-action@v1.1.0
      with:
        dockerfile: ${{ env.DOCKERFILE_PATH }}

    - name: build
      uses: docker/build-push-action@v1.1.0
      with:
        path: ${{ env.SERVICE_ROOT }}
        dockerfile: ${{ env.DOCKERFILE_PATH }}
        repository: ${{ env.DOCKER_REPOSITORY }}
        tag_with_sha: true
        push: false